### PR TITLE
Fix regression in false positive caching of sass_file()

### LINKED ISSUE #84: Using sass_file() can lead to false positive caching
Introduced by https://github.com/rstudio/sass/pull/63  and discovered via https://github.com/rstudio/rmarkdown/issues/2120.

After #63, turns out `sass_file()` can return false-positive cache hits since it no longer includes the modified time in the cache key computation:

```r
withr::with_options(list(sass.cache = TRUE), sass(sass_file("test.scss")))
```

```scss
$main: red;

h1 {
  color: $main;
}
```

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #84

### CODE REVIEW

File: tests/testthat/test-cache.R [hunk 1]
```diff
@@ -24,6 +24,15 @@ test_that("reads from and writes to cache", {
   expect_equal(as.character(css), expected)
 
   expect_equal(sass_cache_get()$size(), 1)
+
+  # Modifying the file busts the cache (even it if has the same contents)
```
Comment (wch) [inline tests/testthat/test-cache.R:28]: If you just need to change the mtime of a file for the test, you can do something like:

```R
Sys.setFileTime(filename, Sys.time() + 5)
```

I used `+ 5` just to be safe.

**Comment by cpsievert** [comment]
When we recently started having `as_sass()` return HTML deps (#74), that should have broken this test expectation

https://github.com/rstudio/sass/blob/489f54586958bb248f82f02434a54d1dfe291980/tests/testthat/test-cache.R#L55-L74

Turns out that test wasn't working the way I intended it to work when I added it in #63, so 
https://github.com/rstudio/sass/pull/85/commits/d1b55e3085304d251b69f3f4efd84c1a27676186 fixes that issue

File: tests/testthat/test-cache.R [hunk 2]
```diff
@@ -24,24 +24,35 @@ test_that("reads from and writes to cache", {
...
-    expect_css(input, css)
+    # Allow input to be an expression, like layer(), that can generate
+    # different input everytime it gets evaluated
+    input_code <- substitute(input)
+    # Did we get the right CSS result?
+    expect_css(eval(input_code), css)
     # Did a cache entry get added?
     expect_equal(cache$size(), 1)
-    # Again, now with an output file
+    # Compile gain, now with an output file
```
Comment (cpsievert) [inline tests/testthat/test-cache.R:47]:
```suggestion
    # Compile again, now with an output file
```

File: R/as_sass.R [hunk 3]
```diff
@@ -81,6 +81,22 @@ find_dependencies <- function(x) {
...
 }
 
+discard_dependencies <- function(x) {
+  if (is_sass_bundle_like(x))  {
+    x <- as_sass_layer(x)
+    x$html_deps <- NULL
+  } else if (is_font_collection(x)) {
+    x$html_deps <- NULL
+  } else {
+    htmlDependencies(x) <- NULL
```
Comment (wch) [inline R/as_sass.R:91]: Note that this won't remove an html dependency if it's included as a child of a tag object (as opposed to being added with `attachDependency()`):

```R
x <- div(
  "hello",
  htmlDependency("x", "1.0", c(src = "abc"))
)
htmlDependencies(x) <- NULL
findDependencies(x)
#> [[1]]
#> List of 10
#>  $ name      : chr "x"
#>  $ version   : chr "1.0"
#>  $ src       :List of 1
#>   ..$ src: chr "abc"
#>  $ meta      : NULL
#>  $ script    : NULL
#>  $ stylesheet: NULL
#>  $ head      : NULL
#>  $ attachment: NULL
#>  $ package   : NULL
#>  $ all_files : logi TRUE
#>  - attr(*, "class")= chr "html_dependency"
```

Same is true if it's an element in a `tagList` or `list`:

```R
x <- tagList(
  div("hello"),
  htmlDependency("x", "1.0", c(src = "abc"))
)
htmlDependencies(x) <- NULL
findDependencies(x)
#> [[1]]
#> List of 10
#>  $ name      : chr "x"
#>  $ version   : chr "1.0"
#>  $ src       :List of 1
#>   ..$ src: chr "abc"
#>  $ meta      : NULL
#>  $ script    : NULL
#>  $ stylesheet: NULL
#>  $ head      : NULL
#>  $ attachment: NULL
#>  $ package   : NULL
#>  $ all_files : logi TRUE
#>  - attr(*, "class")= chr "html_dependency"
```

Comment (cpsievert) [reply R/as_sass.R:91]: I don't think this is an actual issue since `as_sass()` currently doesn't have a method for tags for dependencies (this is partially the motivation for having the `sass_layer(html_deps)`):

```r
> sass::as_sass(list(".foo{}", htmltools::htmlDependency("foo", "1.0", ".")))
Error in as_sass_.default(val) : 
  as_sass() not implemented for object of class: 'html_dependency'
```

That being said, maybe it still make sense to add a case:

```r
} else if (inherits(x, "html_dependency")) {
    x <- NULL
  }
```

just in case we decide to add a no-op method someday
